### ISSUE TITLE
Compute Module Recommended Configuration

### ISSUE THREAD

**Issue by proximitysound** [othermod/PSPi-Version-6#10]
Amazing project.

There are a number of RPi CM4 configurations available with different RAM/Storage options and prices. Is there a recommended spec, or a chart of what the options would offer? I see there’s the SD card slot on the back of the Carrier Board, so I assume the storage is expandable, but wasn’t sure if that’s for other uses.

**Comment by othermod** [comment]
I should add these details to the readme.
I recommend at least 4GB RAM if you want to run an OS like Ubuntu, Kali, etc. If you're just emulating, then anything should work.
If you go with eMMC, it maybe a bit snappier, but you're stuck with whatever space is built in. The SD doesn't work at all on the eMMC version. If you plan to use a lot of space, go with the Lite version and use the SD slot on the Carrier board.
