### ISSUE TITLE
USB Connector

### ISSUE THREAD

**Issue by jneiva08** [othermod/PSPi-Version-6#5]
Hi,

In the bom file couldn't find the part number for the USB connector, can you share the link?
The other question is if you have dxf of the PCBs.

Thanks

**Comment by othermod** [comment]
@jneiva08 The miniUSB connector is listed on here:
https://github.com/othermod/PSPi-Version-6/blob/main/boards/README.md

I'll add the DXF files to the repository.

**Comment by jneiva08** [comment]
Thanks

**Comment by jneiva08** [comment]
Thanks

**Comment by jneiva08** [comment]
Thanks
